# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 55f7fa725c2b02b75aa15aef6dbd0aead3ec2e63ad3be20a3587019db0f3248a77924259d52fd842d5ffd17aebcc68447d2ea29d942ad2e06526e886006cc716

test:
  secret_key_base: 39276a0dedb1d5eb10890c54015c7c53344bdac0c598ed1ee7bd7958bf3e1a14f80b553bec8b836cc09e927fcdf7fd923c53a64b4c5ad9b9f091a8f0fd36867a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
